dist: trusty
language: go
go:
- 1.7
- 1.8
before_install:
- "./scripts/setup"
- go get github.com/mattn/goveralls
install: "./scripts/install"
script:
- "./scripts/test"
- "${HOME}/gopath/bin/goveralls -service=travis-ci"
notifications:
  email:
    on_success: never
    on_failure: always
  slack:
    on_success: change
    on_failure: always
    rooms:
      secure: KPVEWDHePYbCaXwtCtPvLMmpkqRuuqt9D94QS1HN9qk2jYenk0URCtVyTIQPB4kdy7F16IendhB1vEAiOrB9bcs0EM20ciN+MCeOWyDK6ARqdkXFBSzsigQQuHbbe7Um65aHd3usOojD4qpq2E7bzxD21udWDZk/ylD/vOeQ6gJYYaCj6dyEtLS4l228dDBHhOCeSTT3QMljE9aXdM6r/CitDrZkHIsVVBGkEmq2VfNlkyO7IXLs2nYpj1imSpGlpYaZ6ZpkZVlr2cKMZVP2PYShKv94Hpce1Yx4dUmt9UpEGCOrYN4QFgGUq2VHWen++mDTawLo/4Rc+dkPOI/TxwAbCQoR5aNdUuHoQimCIcfJBn73aEar9ZrE+eR4gR0lQEjYvHAvMGJao/7F9rGtRdC871pcuilDOMKYrpgw3JsmDS/cRu5MIavQT0TVG0lC+eMYNiLv5S6d6WAo6mYiZkw6qUeOiFzH04pIkDlQJ2o8WO0Ac8ArNxt1ddsECPjbiaKpAbnx1eIBS9THX3lwsYAW4gCX5W8brsJP4exLtpMuPrxWkR0u0I8cQiI1jzENr/H9oepA3k0/5hC5IQA6QLepFEs4hlh1KBXbqHc90soQchwvgl3ljfd0oyLz8c7C/hkcBiCJ2q68vj9I5mfzxTHsUCW3xQKw/q1CM+/zu3Q=
