dist: trusty
language: go
go:
- 1.7
- 1.8
before_install: "./scripts/setup"
install: "./scripts/install"
script: "./scripts/test"
notifications:
  email:
    on_success: never
    on_failure: always
  slack:
    on_success: change
    on_failure: always
    secure: g00PDFgbvdPk+c9++R8iO5NGpyfk/T40PVDL7xS0q49kNv+/SPbnEyd0xjShKxyr7K7ucQgdSAOhBKtOkHy3zQmMZb5ZxJkQkfsSur+KJ1cTW3fCvCOXj/nlqeErjpTmoMBv5Q8Sj3vtjrF7P/7C8kAuqz3unScbvcj58PclNbAwpCCLVhvSl/MykQMMETL3+tQ+KG1Ngna/1QiWk41fB4w/KnNdY9Bf1aI5XYNYVX7AOJubqplHUcHy6Js4Pnosbu/bq5pIsxLcv1/OYwzlIZuMo+bVE59DODLZX/PLxaJUNGoip/rKOHHtWrNwSkHBgkv3NOlzQaMfysxZ9I2IJPKkG4Z8xjNAEv5yY9DuwkoyVOXGDWMIW7/8UeuI0iUoBhE6dZ2PrDUkClOEwu0NS4W3UX2fwXmZpv8S2iMLvsrWDzhV5iiFSnIQPBAUteq8jn22hQ6opqbDIRIXpB0NBnaovlIa0vNztgmF5PPgnZXR0RkRRe9lOkAWOqP1Xe1QWjc6stSDDRa3buV3VjeCZHh7nQhl4uFBNb6OMBlAxMKGQGv3dgYW1xD7v74V5PF1OhgM+LwAaic3Il00pfQU7HIAhRjk9eg4qLt1tioLq2k9lsQKSz0TWqsFVUnv+BoC/f6EZQltcTFiHjrLBhhMfUOb/wyn6+mOnzHWUoHMkN8=
