#!/usr/bin/env sh

# This should be run on master, ensuring all upstream updates are pulled in.
# This script will re-generate and commit the CHANGELOG.md file, tag HEAD
# with the version you specify, push your changes and tag to origin, and
# create a release on Github using the new tag with the message you specify.
#
# Example: ./scripts/release v0.0.0 "Release Notes Message ..."

set -ex
git tag -s ${1} -m "${2}"
git push --tags
github_changelog_generator --issue-line-labels="ALL" --release-url="https://github.com/hyperdriven/hyperdrive/releases/tag/%s"
git commit CHANGELOG.md -m "updates changelog for ${1}"
git push origin master
hub release create -m "${1}\n\n${2}" ${1}
